### PR TITLE
feature #239 [CoreBundle]: start implemnting required and empty data …

### PR DESCRIPTION
**Pull request by stefan-kamsker**
…option

### CODE REVIEW

**Comment by franzwilding** [comment]
I'm quite sure, that this PR does not what you expect: 

- the required option only adds a HTML5 required attribute. There is no validation, if the value really is present, also for the mutation API, this option was no effect.
- empty_data sets the data if nothing is submitted, as you can read in the docs. I think what we want is to set initial data (there is no symfony form option for this). You implemented a hack in FieldableFormBuilder->createForm() to access settings directly there and manipulate the form. This is not how the field system in unite works. You have two ways to configure the form rendering: return the form type and return form options.

**Comment by stefan-kamsker** [comment]
Hi @franzwilding 

I'm unhappy with this approach (or don't know to do it better with my current sf/unite knowledge), 
even though i like the idea of touching the field type as less as possible

**Problems:**
- I did not achieve to get the parent form with the content object in the form type extension or distinguish between types, so i had to pass the content also to all fields (FieldableFormType.php => **ugly**) $builder>getForm()->getRoot() doesn't help a lot here
- How and where to validate initial data, from my point of view this has to be done in validateSettings, everything else would be to late
- I'm unsure how much more tests should i write, as i would be repetitions and also a lot of work

Ideas:

- writing base Field Types (fe. for choice or all simple string type fields extending FieldType) to do this setting validiation for similar field types
- kick the form type extension and adapt FieldableFormType as this is the place where the childs are added, would be the much easier place for adding constraints and setting initial values

thx

**Comment by franzwilding** [comment]
Why can‘t you just access the root form from any child and then the content Objekt from there?

About testing: have you read this introduction? https://symfony.com/doc/current/testing.html
Generally you should test the code you write. As you didn’t not write so much code, there should also not be too many test cases.

Validating settings must be done in the validateSettings method. Validating content must be implemented in the validate content method

**Comment by stefan-kamsker** [comment]
implemented isNew Method here, you can cherry pick 
https://github.com/unite-cms/unite-cms/pull/337/commits/96583998e07940f59fc2b3648501003196b2693b
in the meantime

**Pull request merged**
